// The range of mdcompose command line versions this release of the extension was
// tested against, checked once at start. Raise the second value after testing a
// newer command line; raise the first only when the extension needs a field that
// older versions do not report. The shared contract samples in integrations/contract
// were generated by the lowest version here.
export const MINIMUM_CLI_VERSION = "0.3.0";
export const HIGHEST_TESTED_CLI_VERSION = "0.3.0";
