// Helpers shared by the adapter tests. Nothing here ships in the extension.
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

// The shared contract samples, generated by the real command line. Tests run
// from the package root, so the samples are one directory up.
export function sample(name: string): unknown {
  const file = join(process.cwd(), "..", "contract", `${name}.json`);
  return JSON.parse(readFileSync(file, "utf8")) as unknown;
}

// A scratch directory that the caller removes with `cleanup`.
export function scratch(prefix = "mdc-adapter-"): { dir: string; cleanup: () => void } {
  const dir = mkdtempSync(join(tmpdir(), prefix));
  return { dir, cleanup: () => rmSync(dir, { recursive: true, force: true }) };
}
