"""The contract between the command line's JSON reports and editor integrations.

Editor integrations read these reports and nothing else, so a field removed or
renamed here breaks every integration at once. The sample documents under
``integrations/contract/`` record the fields integrations may rely on. This test
fails, in this repository's own suite, when a report stops carrying any field a
sample lists. Extra fields in a report are fine: integrations ignore fields they
do not know.

The samples are generated by the real command line. To regenerate them after a
deliberate change, run the suite once with ``MDCOMPOSE_WRITE_CONTRACT_FIXTURES=1``.
"""

from __future__ import annotations

import json
import os
import tempfile
from collections.abc import Callable
from pathlib import Path

import pytest
from conftest import Invocation

from mdcompose.core import platform as platform_module
from mdcompose.core.exit_codes import EXIT_ATTENTION, EXIT_OK

Invoke = Callable[..., Invocation]

CONTRACT_DIRECTORY = Path(__file__).resolve().parents[1] / "integrations" / "contract"
WRITE_VARIABLE = "MDCOMPOSE_WRITE_CONTRACT_FIXTURES"
PLACEHOLDER = "<scratch>"

# The global JSON option goes before the command, which is how integrations call it.
REPORTS: dict[str, tuple[str, ...]] = {
    "doctor": ("--json", "doctor"),
    "snippet-list": ("--json", "snippet", "list"),
    "skill-list": ("--json", "skill", "list"),
    "target-list": ("--json", "target", "list"),
}


@pytest.fixture
def populated(tmp_path: Path, monkeypatch: pytest.MonkeyPatch, invoke: Invoke) -> Path:
    """A project, both libraries, a composed manifest, and one registered target.

    Everything lives under ``tmp_path`` so the reports never see the real machine.
    Returns the scratch root so a sample can be scrubbed of it.
    """
    config_directory = tmp_path / "config"
    snippets = config_directory / "snippets"
    skills = config_directory / "skills"
    snippets.mkdir(parents=True)
    skills.mkdir(parents=True)
    (snippets / "commit-style.md").write_text(
        "---\n"
        "title: Commit style\n"
        "description: How commits are written here\n"
        "tags: [git, conventions]\n"
        "category: conventions\n"
        "---\n\nPrefer small commits.\n",
        encoding="utf-8",
    )
    (snippets / "python-style.md").write_text(
        "---\ntitle: Python style\ntags: [python]\ncategory: languages\n---\n\nUse pathlib.\n",
        encoding="utf-8",
    )
    (skills / "code-review.md").write_text(
        "---\n"
        "title: Code review\n"
        "description: How we review code here\n"
        "tags: [review]\n"
        "category: process\n"
        "---\n\nReview for correctness first.\n",
        encoding="utf-8",
    )
    monkeypatch.setattr(platform_module, "config_dir", lambda: config_directory)
    home = tmp_path / "home"
    (home / ".claude").mkdir(parents=True)
    monkeypatch.setenv("HOME", str(home))
    monkeypatch.setenv("USERPROFILE", str(home))
    project = tmp_path / "project"
    project.mkdir()
    monkeypatch.chdir(project)

    composed = invoke(
        "init", "--yes", "--mode", "copy", "--snippets", "commit-style,python-style"
    )
    assert composed.code == EXIT_OK, composed.err
    agents = home / ".claude" / "AGENTS.md"
    composed_global = invoke(
        "init", "--global", "--yes", "--mode", "copy", "--snippets", "commit-style",
        "--global-agents-path", str(agents),
    )
    assert composed_global.code == EXIT_OK, composed_global.err
    registered = invoke("target", "add", "codex", str(home / ".codex" / "AGENTS.md"))
    assert registered.code == EXIT_OK, registered.err
    return tmp_path


def key_paths(node: object, prefix: str = "") -> set[str]:
    """Every field path in a JSON document, with list elements merged.

    A list of objects contributes the union of its elements' fields, so an
    optional field that appears in only some elements still counts as known.
    """
    paths: set[str] = set()
    if isinstance(node, dict):
        for key, value in node.items():
            path = f"{prefix}.{key}" if prefix else str(key)
            paths.add(path)
            paths |= key_paths(value, path)
    elif isinstance(node, list):
        for element in node:
            paths |= key_paths(element, f"{prefix}[]")
    return paths


def scrub(text: str, root: Path) -> str:
    """Replace the scratch root, in every spelling a report may use, with a placeholder."""
    spellings = {str(root), root.as_posix(), str(root.resolve()), root.resolve().as_posix()}
    for spelling in sorted(spellings, key=len, reverse=True):
        text = text.replace(spelling, PLACEHOLDER)
        text = text.replace(spelling.replace("\\", "\\\\"), PLACEHOLDER)
    return text


def run_report(invoke: Invoke, name: str) -> object:
    """Run one report. A report that finds a problem exits 1 and still prints its document.

    Integrations must therefore read the document on exit code 1 too, and only
    treat other codes, or output that is not JSON, as a failure to report.
    """
    result = invoke(*REPORTS[name])
    assert result.code in {EXIT_OK, EXIT_ATTENTION}, f"{name}: {result.err}"
    return json.loads(result.out)


@pytest.mark.parametrize("name", sorted(REPORTS))
def test_report_still_carries_every_field_its_sample_lists(
    invoke: Invoke, populated: Path, name: str
) -> None:
    document = run_report(invoke, name)
    sample_file = CONTRACT_DIRECTORY / f"{name}.json"
    if os.environ.get(WRITE_VARIABLE):
        CONTRACT_DIRECTORY.mkdir(parents=True, exist_ok=True)
        text = scrub(json.dumps(document, indent=2, ensure_ascii=True), populated)
        sample_file.write_text(text + "\n", encoding="utf-8", newline="\n")
    sample = json.loads(sample_file.read_text(encoding="utf-8"))
    missing = sorted(key_paths(sample) - key_paths(document))
    assert not missing, (
        f"the {name} report no longer carries fields that {sample_file.name} lists: "
        f"{', '.join(missing)}. Editor integrations read these fields. If the change is "
        f"deliberate, update the sample and the integrations together."
    )


@pytest.mark.parametrize("name", sorted(REPORTS))
def test_sample_holds_no_path_from_the_machine_that_generated_it(name: str) -> None:
    text = (CONTRACT_DIRECTORY / f"{name}.json").read_text(encoding="utf-8")
    forbidden = {
        Path.home().as_posix(),
        str(Path.home()).replace("\\", "\\\\"),
        Path(tempfile.gettempdir()).as_posix(),
        str(Path(tempfile.gettempdir())).replace("\\", "\\\\"),
    }
    for path in forbidden:
        assert path not in text, f"{name}.json contains the local path {path}"


@pytest.mark.parametrize("name", sorted(REPORTS))
def test_sample_is_one_valid_json_document(name: str) -> None:
    text = (CONTRACT_DIRECTORY / f"{name}.json").read_text(encoding="utf-8")
    assert isinstance(json.loads(text), dict)


def test_key_paths_merge_the_fields_of_list_elements() -> None:
    document = {"rows": [{"a": 1}, {"a": 2, "b": 3}], "flag": True}
    assert key_paths(document) == {"rows", "rows[].a", "rows[].b", "flag"}


def test_key_paths_of_a_scalar_list_stop_at_the_list() -> None:
    assert key_paths({"tags": ["x", "y"]}) == {"tags"}


def test_scrub_replaces_the_root_in_both_path_spellings(tmp_path: Path) -> None:
    text = f'{tmp_path.as_posix()}/cfg and {str(tmp_path).replace(chr(92), chr(92) * 2)}'
    assert PLACEHOLDER in scrub(text, tmp_path)
    assert str(tmp_path) not in scrub(text, tmp_path)
